/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.AtraccionControlador;
import controlador.VisitasControlador;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Atraccion;
import modelo.Cliente;
import modelo.Tiquete;
import modelo.Visitas;

/**
 *
 * @author Heidy
 */
public class VistaMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form vistaMantenimiento
     */
    public VistaMantenimiento() {
        initComponents();
        setTitle("Mantenimiento");
        cargarAtraccionesEnTabla(tablaAtracciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAtracciones = new javax.swing.JTable();
        txtEstado = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtAtraccionId = new javax.swing.JTextField();
        btnLeerTodas = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Atracciones");

        jLabel1.setText("Aquí podrás gestionar el estado de cada atracción");

        tablaAtracciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "atraccion_id", "nombre", "estado"
            }
        ));
        jScrollPane1.setViewportView(tablaAtracciones);

        txtEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitada", "Daño", "Mantenimiento" }));

        btnActualizar.setText("Actualizar estado");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel3.setText("atraccion_id");

        btnLeerTodas.setText("Leer todas");
        btnLeerTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerTodasActionPerformed(evt);
            }
        });

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel4.setText("estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAtraccionId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnActualizar)
                                    .addComponent(btnLeerTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtras)))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(jLabel3)
                    .addComponent(txtAtraccionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLeerTodas)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeerTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerTodasActionPerformed
        cargarAtraccionesEnTabla(tablaAtracciones);
    }//GEN-LAST:event_btnLeerTodasActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int atraccionId = Integer.parseInt(txtAtraccionId.getText());
        String estadoAtraccion = (String) txtEstado.getSelectedItem();
        
        AtraccionControlador atraccionControlador = new AtraccionControlador();
        Atraccion atraccion = atraccionControlador.obtenerAtraccionPorId(atraccionId);
        
        Atraccion nuevaAtraccion = new Atraccion(atraccion.getId(),atraccion.getNombre(), atraccion.getDescripcion(), atraccion.getClasificacion(), atraccion.getCondicionesUso(),estadoAtraccion,atraccion.getAlturaMinima());
        atraccionControlador.actualizarAtraccion(atraccionId, nuevaAtraccion);
        
        JOptionPane.showMessageDialog(this, "Atracción actualizada correctamente.");
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        dispose();
        VistaEmpleado vistaEmpleado = new VistaEmpleado();
        vistaEmpleado.setLocationRelativeTo(null);
        vistaEmpleado.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed
    
    public void cargarAtraccionesEnTabla(javax.swing.JTable tablaAtracciones) {
        // Obtener el modelo asociado a la tabla proporcionada
        DefaultTableModel modelo = (DefaultTableModel) tablaAtracciones.getModel();

        // Limpiar todas las filas existentes en la tabla
        modelo.setRowCount(0);

        // Instanciar el controlador de atracciones para acceder a los datos
        AtraccionControlador atraccionControlador = new AtraccionControlador();
        List<Atraccion> atracciones = atraccionControlador.obtenerTodasLasAtracciones();

        // Iterar sobre la lista de atracciones y agregar cada una como una fila a la tabla
        for (Atraccion atraccion : atracciones) { 
            modelo.addRow(new Object[]{
                atraccion.getId(),      // ID único de la atracción
                atraccion.getNombre(),  // Nombre descriptivo de la atracción
                atraccion.getEstado()   // Estado actual de la atracción (e.g., activa/inactiva)
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnLeerTodas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAtracciones;
    private javax.swing.JTextField txtAtraccionId;
    private javax.swing.JComboBox<String> txtEstado;
    // End of variables declaration//GEN-END:variables
}
